### ISSUE TITLE
スレッドの deploy に失敗する

### ISSUE THREAD

**Issue by okapies** [revoltage-inc/msd-cli#53]
`npm run deploy:migrate` の実行時に、下記のエラーが出て失敗することがあります。

```
✔️ Check parameter
✔️ Create client
⠸ Deploy message
× Deploy message
Error: Failed to get thread message
    at MessageClient.deployMessage (file:///home/user/msd-cli/libs/message.mts:280:17)
    at async MessageClient.deployManyMessage (file:///home/user/msd-cli/libs/message.mts:213:7)
    at async MessageClient.deployAllMessage (file:///home/user/msd-cli/libs/message.mts:195:9)
    at async file:///home/user/msd-cli/command/deploy/message.mts:55:5
```

`deployId` が取れないことが原因のようなのですが、本来、ここにはどのような値が入っているべきなのでしょうか。回避策をご教示いただきたく。

![Screenshot from 2022-08-31 22-51-23](https://user-images.githubusercontent.com/657642/187695159-e39141da-c2f9-4f4a-bf44-e2c4a498bd3c.png)

**Comment by yogarasu** [comment]
@okapies 
issueありがとうございます
DeployIdには、Discordにメッセージをデプロイした場合のメッセージIDが入る想定です

そこのエラーが出るということが該当メッセージが、リプライメッセージにも関わらず、
何らかの問題でデプロイされている(はずの)リプライ先のメッセージ情報が取得できていないということになります

https://github.com/revoltage-inc/msd-cli/blob/main/libs/message.mts#L280

まずはエラーが出たリプライメッセージのリプライ先のメッセージがデプロイされているか(DeployIdが入っているか)を確認していただき、
もしDeployIdが入っている場合は、エラーが出たリプライメッセージとリプライ先のメッセージのDBカラムの内容(個人情報的にメッセージ内容を伏せたもの)を教えてください
少し原因を探ってみます

**Comment by okapies** [comment]
ご回答ありがとうございます。6行目の親メッセージが上から4行目なので、確かに入っていないと思います。親メッセージ自体は Discord に書き込まれていた記憶があるので、Discord には書き込まれたが Deploy ID が DB に書き込まれていない状況かもしれません。もう一度やり直してみたほうがよいでしょうか？ どこかに進捗を記録しているテーブルがありましたら、そのテーブル名を教えていただきたく。

**Comment by yogarasu** [comment]
@okapies 
もし書き込みが失敗しているようならエラーが発生すると思うので、少しイレギュラーな状態ですね
特に進捗を記載しているテーブルはありません

MessageテーブルにDeployIDが入っているかいないかでデプロイされたかされていないかを判断していて、
一応はデプロイをリトライできるようにデプロイ対象取得時にDeployIDが入っている(=デプロイされている)ものは除外する仕組みにはなっていますが、念の為やり直しした方が良いと思います

もし親メッセージがDiscordに書き込まれていない場合であれば、
リプライメッセージの性質上、親メッセージの後に子メッセージという時系列順にデプロイされる必要があるにも関わらず、
取得時もしくはデプロイ時に子メッセージの方がなぜか先に来ているという1番疑いが高い仮説が成り立つので
こちらも再度併せてご確認ください
