### ISSUE TITLE
Readyイベント発火前にguilds.cacheの取得をしている

### ISSUE THREAD

**Issue by i4M1k0SU** [revoltage-inc/msd-cli#57]
現状の仕様であれば問題になることは無いのかもしれないが、

厳密性と今後の拡張性を考えreadyイベントが終わるまで待つようにした方が良いように思います。

## 実装例

libs/client.mts内のL26  `await client.login(discordBotToken)` 後に以下を入れる

```ts
await new Promise<void>(resolve => client.on('ready', () => resolve()));
```

**Comment by yogarasu** [comment]
@i4M1k0SU 
ありがとうございます

チェーン構造でプロパティにアクセスしていく仕様ですし、
discord.jsの例を見ても、readyイベントが終わるまで待つようになっているのでそれに準じるように修正しました

**Comment by yogarasu** [comment]
#77 の問題が起こるようになったので#64 で一旦該当箇所をコメントアウトします
