### ISSUE TITLE
Embedの改善提案

### ISSUE THREAD

**Issue by i4M1k0SU** [revoltage-inc/msd-cli#64]
# 本文をfieldからdescriptionへ置き換え

区切りの挿入のためかfieldを使っていますが、fieldの文字数制限は1024文字です

descriptionに置き換えることで4096文字まで制限が緩和されます。

また、こちらの方が用途としても正しいです。

# 時刻をfooterへ移動

現状は投稿時刻をauthorに入れていますが、footerに入れることでtimestampの日付と並び、より自然に表示できるように思います。

## 例
![image](https://user-images.githubusercontent.com/7927400/188295449-54f9e15a-adfc-4071-9ade-d170d4779dec.png)

**Comment by yogarasu** [comment]
@i4M1k0SU 
提案ありがとうございます

確かにdescriptionの方が良いですね
ただ#13 に記載していますが、Slackは12000文字まで入力可能のようなので、
1024文字以上丸める処理は4096文字以上にして継続することにしました
この制限に引っかかることは稀だと思うので暫定対応ですが、引っかかるケースが多ければ
その都度、分割するなり別途検討しようと思います

投稿時刻はtimestampだと日付検索できて嬉しいですが、
日本語だと今日や明日といった単語になり、見づらい時も感じていたため、footerにも追加するように修正しました
