### ISSUE TITLE
表示名が設定されていない場合にエラーが出る

### ISSUE THREAD

**Issue by faceoff24** [revoltage-inc/msd-cli#65]
便利なものを作っていただきありがとうございます。

Slackで表示名を設定していないユーザーがいる場合、migrate:messageで以下のエラーが出るようです。

> $ npm run migrate:message
（略）
× Migrate message
Error: Failed to replace mention of @zzzzzz to username
    at MessageClient.convertMessageContent (file:///Users/zzzzz/msd-cli/libs/message.mts:474:17)
    at async MessageClient.migrateAllMessage (file:///Users/zzzzz/msd-cli/libs/message.mts:79:27)
    at async file:///Users/zzzzz/msd-cli/command/migrate/message.mts:53:5

users.jsonの"display_name": ""に値を入れるか、mds.sqliteのUserテーブルのnameに値を入れることで解消しましたが、migrate:userを走らせた際に"display_name"が空欄の場合には"real_name"から値を取ってくるなどの処理があると良さそうです。

コーディングなどはさっぱりわからず、Github触るのも初めてなので、Issueの上げ方などに問題あったらご容赦ください。

**Comment by TatsuyaShirakawa** [comment]
私も同じ問題にあたって、ご提案と同じ下記の方法で解決しました。

`libs/user.mts` の 55 行目を
```typescript
  : user.profile.display_name,
```
から
```typescript
  : (user.profile.display_name || user.profile.real_name)
```
などにすると動作するようになるはずです。
（[Pull Request](https://github.com/revoltage-inc/msd-cli/pull/73)も作っておきました）

**Comment by yogarasu** [comment]
TatsuyaShirakawaさんからいただいた #73 のプルリクをマージして、解消したと思うのでクローズします

**Comment by faceoff24** [comment]
対応ありがとうございます！！
