### ISSUE TITLE
Error: Failed to get thread messageについて

### ISSUE THREAD

**Issue by IWANKO23** [revoltage-inc/msd-cli#75]
## 🐞 Bug Report

素晴らしいツールをありがとうございます

データ移行時にError: Failed to get thread messageが出てしまい困っていました。
色々と状況を確認したところ、元のログで発言無しの添付ファイルに対してリプライがついた時に返信先が無くなりエラーが出ていたようでした
自力でコードを修正することができなかったため、ログを少し書き換えて対応しました

**Comment by yogarasu** [comment]
@IWANKO23 
ご報告ありがとうございます
現象再現できましたので数日中に修正します
