### ISSUE TITLE
コマンドがクライアント作成から進まない

### ISSUE THREAD

**Issue by yogarasu** [revoltage-inc/msd-cli#77]
### Bug content 

#57  でClientにReady処理を入れてから、たまにCLIのコマンドがクライアント作成から進まない場合がある
#64で一旦コメントアウトしているが、そもそもReady処理は必要か、必要であれば記法は正しいか再度要調査

**Comment by i4M1k0SU** [comment]
私は絵文字投稿を移行できる処理を自前実装して使いましたが、その際readyイベント後でないとサーバ内の絵文字を取得できないようでした

クライアント作成から進まない場合、loginとreadyイベントのタイミングによって既にreadyイベントが発火済みの可能性があります

以下のようにすれば確実に両方の処理を待つようになると思います

```js
await Promise.all([
    new Promise<void>((resolve) => client.on("ready", () => resolve())),
    client.login(discordBotToken)
]);
```

**Comment by yogarasu** [comment]
@i4M1k0SU 

そのコードを試しましたが解決せず、そもそもreadyイベントが発火していない様子です

メンテナーによるとReadyイベントをPromiseでラップするのはあまり推奨されていないようです
https://github.com/discordjs/discord.js/issues/5258#issuecomment-766399954

詳細な理由はわかりませんが、おそらくここら辺が理由かもしれません
https://stackoverflow.com/questions/29501249/waiting-for-events-with-a-promise

**Comment by yogarasu** [comment]
discord.jsのdiscordサーバーのproficientに`node:events`のonceを使ったやり方を教えてもらいました

```ts
import { once } from "node:events"
// ...
await once(client, "ready")
```

ドキュメントを見る限り、ユースケースとしては合っていて、client.onやclient.onceより汎用的に扱いやすく、
クライアントの処理が止まることがないので、こちらに修正と思います
https://nodejs.org/api/events.html#eventsonceemitter-name-options

**Comment by yogarasu** [comment]
稀に再発することを確認したので再度オープン
